import '../models/station.dart';

class WaterService {
  static List<Station> getStations() {
    return [
      Station(
        id: "1",
        name: "Baziaș",
        river: "Dunărea",
        level: 248,
        trend: WaterTrend.rising,
        latitude: 44.816,
        longitude: 21.383,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "2",
        name: "Moldova Veche",
        river: "Dunărea",
        level: 262,
        trend: WaterTrend.falling,
        latitude: 44.723,
        longitude: 21.626,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "3",
        name: "Orșova",
        river: "Dunărea",
        level: 301,
        trend: WaterTrend.rising,
        latitude: 44.725,
        longitude: 22.396,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "4",
        name: "Drobeta",
        river: "Dunărea",
        level: 287,
        trend: WaterTrend.stable,
        latitude: 44.636,
        longitude: 22.659,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "5",
        name: "Calafat",
        river: "Dunărea",
        level: 315,
        trend: WaterTrend.rising,
        latitude: 43.991,
        longitude: 22.933,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "6",
        name: "Bechet",
        river: "Dunărea",
        level: 298,
        trend: WaterTrend.falling,
        latitude: 43.790,
        longitude: 23.957,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "7",
        name: "Corabia",
        river: "Dunărea",
        level: 281,
        trend: WaterTrend.rising,
        latitude: 43.774,
        longitude: 24.504,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "8",
        name: "Turnu Măgurele",
        river: "Dunărea",
        level: 294,
        trend: WaterTrend.rising,
        latitude: 43.751,
        longitude: 24.871,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "9",
        name: "Giurgiu",
        river: "Dunărea",
        level: 336,
        trend: WaterTrend.stable,
        latitude: 43.903,
        longitude: 25.969,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "10",
        name: "Oltenița",
        river: "Dunărea",
        level: 322,
        trend: WaterTrend.falling,
        latitude: 44.083,
        longitude: 26.637,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "11",
        name: "Călărași",
        river: "Dunărea",
        level: 340,
        trend: WaterTrend.rising,
        latitude: 44.205,
        longitude: 27.333,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "12",
        name: "Cernavodă",
        river: "Dunărea",
        level: 352,
        trend: WaterTrend.rising,
        latitude: 44.339,
        longitude: 28.032,
        lastUpdate: DateTime.now(),
      ),
      Station(
        id: "13",
        name: "Tulcea",
        river: "Dunărea",
        level: 365,
        trend: WaterTrend.stable,
        latitude: 45.171,
        longitude: 28.791,
        lastUpdate: DateTime.now(),
      ),
    ];
  }
}
