import 'package:flutter/material.dart';

import '../navigation/app_destination.dart';

enum FluviUtilityFamily {
  waterIntelligence,
  mapExploration,
  weatherSolunar,
  fluviAi,
  communityReports,
  catchesJournal,
  myWatersFavorites,
  rulesPermitsSafety,
  accountSettings,
}

enum FluviEntitlementPolicy { free, premiumDepth, premiumOnly }

enum FluviOfflinePolicy { onlineOnly, cachedRead, queuedWrite, localFirst }

enum FluviPrivacyPolicy {
  notApplicable,
  privateDefault,
  exactApproximateHidden,
  aggregatedOnly,
}

enum FluviUtilityMaturity { beta, progressive }

class FluviUtilityDefinition {
  const FluviUtilityDefinition({
    required this.id,
    required this.family,
    required this.destination,
    required this.titleRo,
    required this.titleEn,
    required this.subtitleRo,
    required this.subtitleEn,
    required this.icon,
    required this.contexts,
    required this.countryPacks,
    required this.entitlement,
    required this.offlinePolicy,
    required this.privacyPolicy,
    this.permissions = const <String>{},
    this.searchable = true,
    this.pinnable = true,
    this.quickAction = false,
    this.safetyCritical = false,
    this.maturity = FluviUtilityMaturity.beta,
  });

  final String id;
  final FluviUtilityFamily family;
  final AppDestination destination;
  final String titleRo;
  final String titleEn;
  final String subtitleRo;
  final String subtitleEn;
  final IconData icon;
  final Set<String> contexts;
  final Set<String> countryPacks;
  final FluviEntitlementPolicy entitlement;
  final FluviOfflinePolicy offlinePolicy;
  final FluviPrivacyPolicy privacyPolicy;
  final Set<String> permissions;
  final bool searchable;
  final bool pinnable;
  final bool quickAction;
  final bool safetyCritical;
  final FluviUtilityMaturity maturity;

  String title(bool isRomanian) => isRomanian ? titleRo : titleEn;

  String subtitle(bool isRomanian) => isRomanian ? subtitleRo : subtitleEn;
}

extension FluviUtilityFamilyCopy on FluviUtilityFamily {
  String title(bool isRomanian) => switch (this) {
    FluviUtilityFamily.waterIntelligence =>
      isRomanian ? 'Inteligența apei' : 'Water Intelligence',
    FluviUtilityFamily.mapExploration =>
      isRomanian ? 'Hartă și explorare' : 'Map & Exploration',
    FluviUtilityFamily.weatherSolunar =>
      isRomanian ? 'Vreme și solunar' : 'Weather & Solunar',
    FluviUtilityFamily.fluviAi => isRomanian ? 'Fluvi și AI' : 'Fluvi & AI',
    FluviUtilityFamily.communityReports =>
      isRomanian ? 'Comunitate și rapoarte' : 'Community & Reports',
    FluviUtilityFamily.catchesJournal =>
      isRomanian ? 'Capturi și jurnal' : 'Catches & Journal',
    FluviUtilityFamily.myWatersFavorites =>
      isRomanian ? 'Apele mele și favorite' : 'My Waters & Favorites',
    FluviUtilityFamily.rulesPermitsSafety =>
      isRomanian ? 'Reguli, permise și siguranță' : 'Rules, Permits & Safety',
    FluviUtilityFamily.accountSettings =>
      isRomanian ? 'Cont și setări' : 'Account & Settings',
  };

  IconData get icon => switch (this) {
    FluviUtilityFamily.waterIntelligence => Icons.water_rounded,
    FluviUtilityFamily.mapExploration => Icons.map_rounded,
    FluviUtilityFamily.weatherSolunar => Icons.cloud_rounded,
    FluviUtilityFamily.fluviAi => Icons.auto_awesome_rounded,
    FluviUtilityFamily.communityReports => Icons.groups_rounded,
    FluviUtilityFamily.catchesJournal => Icons.set_meal_rounded,
    FluviUtilityFamily.myWatersFavorites => Icons.bookmark_rounded,
    FluviUtilityFamily.rulesPermitsSafety => Icons.health_and_safety_rounded,
    FluviUtilityFamily.accountSettings => Icons.tune_rounded,
  };
}

abstract final class FluviUtilityRegistry {
  static const _global = <String>{'RO', 'UK', 'EU'};
  static const _allContexts = <String>{
    'plan',
    'travel',
    'fish',
    'capture',
    'review',
  };

  static const definitions = <FluviUtilityDefinition>[
    FluviUtilityDefinition(
      id: 'water.overview',
      family: FluviUtilityFamily.waterIntelligence,
      destination: AppDestination.water,
      titleRo: 'Niveluri și trend',
      titleEn: 'Levels & trend',
      subtitleRo: 'Nivel, deltă, debit, temperatură și prospețime',
      subtitleEn: 'Level, delta, flow, temperature and freshness',
      icon: Icons.show_chart_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.notApplicable,
    ),
    FluviUtilityDefinition(
      id: 'water.hydro-pulse',
      family: FluviUtilityFamily.waterIntelligence,
      destination: AppDestination.water,
      titleRo: 'Pulsul apei',
      titleEn: 'Hydro Pulse',
      subtitleRo: 'Creștere, scădere și uzinare probabilă',
      subtitleEn: 'Rising, falling and likely controlled release',
      icon: Icons.waves_rounded,
      contexts: <String>{'plan', 'travel', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.premiumDepth,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.aggregatedOnly,
      safetyCritical: true,
    ),
    FluviUtilityDefinition(
      id: 'water.stations',
      family: FluviUtilityFamily.waterIntelligence,
      destination: AppDestination.water,
      titleRo: 'Stații hidrometrice',
      titleEn: 'Water stations',
      subtitleRo: 'Stații oficiale, surse și observații recente',
      subtitleEn: 'Official stations, sources and recent observations',
      icon: Icons.speed_rounded,
      contexts: <String>{'plan', 'travel', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.notApplicable,
    ),
    FluviUtilityDefinition(
      id: 'water.reservoirs',
      family: FluviUtilityFamily.waterIntelligence,
      destination: AppDestination.reservoir,
      titleRo: 'Baraje și acumulări',
      titleEn: 'Dams & reservoirs',
      subtitleRo: 'Entități legate de râuri și stații amonte/aval',
      subtitleEn: 'Entities linked to rivers and upstream/downstream stations',
      icon: Icons.account_balance_rounded,
      contexts: <String>{'plan', 'travel'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.premiumDepth,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.notApplicable,
    ),
    FluviUtilityDefinition(
      id: 'water.hydropower',
      family: FluviUtilityFamily.waterIntelligence,
      destination: AppDestination.hydropower,
      titleRo: 'Hidrocentrale',
      titleEn: 'Hydropower',
      subtitleRo: 'Context operațional și efecte observate în aval',
      subtitleEn: 'Operational context and observed downstream effects',
      icon: Icons.electric_bolt_rounded,
      contexts: <String>{'plan', 'travel', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.premiumDepth,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.aggregatedOnly,
      maturity: FluviUtilityMaturity.progressive,
    ),
    FluviUtilityDefinition(
      id: 'map.full',
      family: FluviUtilityFamily.mapExploration,
      destination: AppDestination.map,
      titleRo: 'Harta completă',
      titleEn: 'Full map',
      subtitleRo: 'Ape, stații, acces, rapoarte și locuri private',
      subtitleEn: 'Waters, stations, access, reports and private places',
      icon: Icons.map_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.exactApproximateHidden,
      permissions: <String>{'location'},
    ),
    FluviUtilityDefinition(
      id: 'map.search',
      family: FluviUtilityFamily.mapExploration,
      destination: AppDestination.search,
      titleRo: 'Căutare globală',
      titleEn: 'Global search',
      subtitleRo: 'Ape, stații, localități, specii și utilități',
      subtitleEn: 'Waters, stations, places, species and utilities',
      icon: Icons.search_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.notApplicable,
    ),
    FluviUtilityDefinition(
      id: 'map.access',
      family: FluviUtilityFamily.mapExploration,
      destination: AppDestination.map,
      titleRo: 'Acces și mal',
      titleEn: 'Access & bank',
      subtitleRo: 'Parcare, intrare, traseu, obstacole și acces legal',
      subtitleEn: 'Parking, entry, route, obstacles and legal access',
      icon: Icons.directions_walk_rounded,
      contexts: <String>{'plan', 'travel', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.queuedWrite,
      privacyPolicy: FluviPrivacyPolicy.exactApproximateHidden,
      permissions: <String>{'location'},
    ),
    FluviUtilityDefinition(
      id: 'weather.forecast',
      family: FluviUtilityFamily.weatherSolunar,
      destination: AppDestination.weather,
      titleRo: 'Vreme pentru pescuit',
      titleEn: 'Fishing weather',
      subtitleRo: 'Vânt, rafale, presiune, ploaie și avertizări',
      subtitleEn: 'Wind, gusts, pressure, rain and warnings',
      icon: Icons.cloud_rounded,
      contexts: <String>{'plan', 'travel', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.notApplicable,
    ),
    FluviUtilityDefinition(
      id: 'weather.solunar',
      family: FluviUtilityFamily.weatherSolunar,
      destination: AppDestination.weather,
      titleRo: 'Solunar și lumină',
      titleEn: 'Solunar & light',
      subtitleRo: 'Răsărit, apus, lună și ferestre de activitate',
      subtitleEn: 'Sunrise, sunset, moon and activity windows',
      icon: Icons.nightlight_round,
      contexts: <String>{'plan', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.notApplicable,
    ),
    FluviUtilityDefinition(
      id: 'fluvi.score',
      family: FluviUtilityFamily.fluviAi,
      destination: AppDestination.fluvi,
      titleRo: 'FluviScore',
      titleEn: 'FluviScore',
      subtitleRo: 'Șanse de pescuit acum, explicate prin factori reali',
      subtitleEn: 'Fishing conditions now, explained by real factors',
      icon: Icons.speed_rounded,
      contexts: <String>{'plan', 'travel', 'fish', 'review'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
    ),
    FluviUtilityDefinition(
      id: 'fluvi.insight',
      family: FluviUtilityFamily.fluviAi,
      destination: AppDestination.fluvi,
      titleRo: 'Fluvi Insight',
      titleEn: 'Fluvi Insight',
      subtitleRo: 'Ce ajută, ce reduce șansele și câtă încredere avem',
      subtitleEn: 'What helps, what reduces the odds and confidence',
      icon: Icons.insights_rounded,
      contexts: <String>{'plan', 'travel', 'fish', 'review'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.premiumDepth,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
    ),
    FluviUtilityDefinition(
      id: 'fluvi.ask',
      family: FluviUtilityFamily.fluviAi,
      destination: AppDestination.askFluvi,
      titleRo: 'Întreabă Fluvi',
      titleEn: 'Ask Fluvi',
      subtitleRo: 'Întrebări despre apă, vreme, reguli și partidă',
      subtitleEn: 'Questions about water, weather, rules and sessions',
      icon: Icons.chat_bubble_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.premiumDepth,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
    ),
    FluviUtilityDefinition(
      id: 'fluvi.vision',
      family: FluviUtilityFamily.fluviAi,
      destination: AppDestination.addCatch,
      titleRo: 'Fluvi Vision',
      titleEn: 'Fluvi Vision',
      subtitleRo: 'Sugestie specie, calitatea fotografiei și confirmare',
      subtitleEn: 'Species suggestion, photo quality and confirmation',
      icon: Icons.center_focus_strong_rounded,
      contexts: <String>{'capture', 'review'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.localFirst,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
      permissions: <String>{'camera'},
      quickAction: true,
    ),
    FluviUtilityDefinition(
      id: 'community.feed',
      family: FluviUtilityFamily.communityReports,
      destination: AppDestination.community,
      titleRo: 'Comunitate',
      titleEn: 'Community',
      subtitleRo: 'Semnale regionale, confirmări și interpretare',
      subtitleEn: 'Regional signals, confirmations and interpretation',
      icon: Icons.groups_rounded,
      contexts: <String>{'plan', 'travel', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.aggregatedOnly,
    ),
    FluviUtilityDefinition(
      id: 'reports.add',
      family: FluviUtilityFamily.communityReports,
      destination: AppDestination.addReport,
      titleRo: 'Raport rapid',
      titleEn: 'Quick report',
      subtitleRo: 'Apă, acces, pericol, poluare sau activitate',
      subtitleEn: 'Water, access, hazard, pollution or activity',
      icon: Icons.outlined_flag_rounded,
      contexts: <String>{'travel', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.queuedWrite,
      privacyPolicy: FluviPrivacyPolicy.exactApproximateHidden,
      permissions: <String>{'location', 'camera'},
      quickAction: true,
    ),
    FluviUtilityDefinition(
      id: 'reports.mine',
      family: FluviUtilityFamily.communityReports,
      destination: AppDestination.myReports,
      titleRo: 'Rapoartele mele',
      titleEn: 'My reports',
      subtitleRo: 'Active, expirate, confirmate și salvate offline',
      subtitleEn: 'Active, expired, confirmed and saved offline',
      icon: Icons.inventory_2_rounded,
      contexts: <String>{'plan', 'review'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.queuedWrite,
      privacyPolicy: FluviPrivacyPolicy.exactApproximateHidden,
    ),
    FluviUtilityDefinition(
      id: 'catches.add',
      family: FluviUtilityFamily.catchesJournal,
      destination: AppDestination.addCatch,
      titleRo: 'Adaugă captură',
      titleEn: 'Add catch',
      subtitleRo: 'Foto, specie, măsurători și locație privată',
      subtitleEn: 'Photo, species, measurements and private location',
      icon: Icons.add_a_photo_rounded,
      contexts: <String>{'fish', 'capture'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.localFirst,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
      permissions: <String>{'camera', 'location'},
      quickAction: true,
    ),
    FluviUtilityDefinition(
      id: 'catches.mine',
      family: FluviUtilityFamily.catchesJournal,
      destination: AppDestination.myCatches,
      titleRo: 'Capturile mele',
      titleEn: 'My catches',
      subtitleRo: 'Capturi private, statistici și corectări AI',
      subtitleEn: 'Private catches, statistics and AI corrections',
      icon: Icons.photo_library_rounded,
      contexts: <String>{'plan', 'review'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.localFirst,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
    ),
    FluviUtilityDefinition(
      id: 'journal.sessions',
      family: FluviUtilityFamily.catchesJournal,
      destination: AppDestination.journal,
      titleRo: 'Jurnal de pescuit',
      titleEn: 'Fishing journal',
      subtitleRo: 'Partide, capturi, observații și analiză personală',
      subtitleEn: 'Sessions, catches, observations and personal analysis',
      icon: Icons.menu_book_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.localFirst,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
    ),
    FluviUtilityDefinition(
      id: 'journal.bite-effort',
      family: FluviUtilityFamily.catchesJournal,
      destination: AppDestination.journal,
      titleRo: 'Trăsături și efort',
      titleEn: 'Bites & effort',
      subtitleRo: 'Indisponibil până la conectarea unui jurnal real',
      subtitleEn: 'Unavailable until a real journal is connected',
      icon: Icons.timeline_rounded,
      contexts: <String>{'fish', 'review'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.localFirst,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
      quickAction: true,
    ),
    FluviUtilityDefinition(
      id: 'favorites.my-waters',
      family: FluviUtilityFamily.myWatersFavorites,
      destination: AppDestination.favorites,
      titleRo: 'Apele mele',
      titleEn: 'My waters',
      subtitleRo: 'Ape, stații, locuri, colecții și alerte urmărite',
      subtitleEn: 'Waters, stations, places, collections and followed alerts',
      icon: Icons.bookmark_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.localFirst,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
    ),
    FluviUtilityDefinition(
      id: 'alerts.center',
      family: FluviUtilityFamily.myWatersFavorites,
      destination: AppDestination.alerts,
      titleRo: 'Alerte',
      titleEn: 'Alerts',
      subtitleRo: 'Nivel, trend, vreme, siguranță și apă urmărită',
      subtitleEn: 'Level, trend, weather, safety and followed water',
      icon: Icons.notifications_active_rounded,
      contexts: <String>{'plan', 'travel', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
      permissions: <String>{'notifications'},
      safetyCritical: true,
    ),
    FluviUtilityDefinition(
      id: 'rules.can-fish-now',
      family: FluviUtilityFamily.rulesPermitsSafety,
      destination: AppDestination.regulations,
      titleRo: 'Pot pescui aici acum?',
      titleEn: 'Can I fish here now?',
      subtitleRo: 'Sezon, specie, metode, limite și sursa regulii',
      subtitleEn: 'Season, species, methods, limits and rule source',
      icon: Icons.rule_rounded,
      contexts: <String>{'plan', 'travel', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.notApplicable,
      safetyCritical: true,
    ),
    FluviUtilityDefinition(
      id: 'rules.permits',
      family: FluviUtilityFamily.rulesPermitsSafety,
      destination: AppDestination.permit,
      titleRo: 'Permise și sezoane',
      titleEn: 'Permits & seasons',
      subtitleRo: 'Autoritate, permis necesar și perioade legale',
      subtitleEn: 'Authority, required permission and legal periods',
      icon: Icons.badge_rounded,
      contexts: <String>{'plan', 'travel'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.notApplicable,
    ),
    FluviUtilityDefinition(
      id: 'safety.ready-to-fish',
      family: FluviUtilityFamily.rulesPermitsSafety,
      destination: AppDestination.home,
      titleRo: 'Gata de pescuit',
      titleEn: 'Ready to fish',
      subtitleRo: 'Reguli, apă, vreme, acces, offline și baterie',
      subtitleEn: 'Rules, water, weather, access, offline and battery',
      icon: Icons.checklist_rounded,
      contexts: <String>{'plan'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.localFirst,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
    ),
    FluviUtilityDefinition(
      id: 'safety.check-in',
      family: FluviUtilityFamily.rulesPermitsSafety,
      destination: AppDestination.safety,
      titleRo: 'Check-in de siguranță',
      titleEn: 'Safety check-in',
      subtitleRo: 'Contact de încredere și ora estimată de întoarcere',
      subtitleEn: 'Trusted contact and expected return time',
      icon: Icons.share_location_rounded,
      contexts: <String>{'travel', 'fish'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.localFirst,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
      permissions: <String>{'location', 'notifications'},
      safetyCritical: true,
      maturity: FluviUtilityMaturity.progressive,
    ),
    FluviUtilityDefinition(
      id: 'safety.fish-welfare',
      family: FluviUtilityFamily.rulesPermitsSafety,
      destination: AppDestination.safety,
      titleRo: 'Protecția peștelui',
      titleEn: 'Fish welfare',
      subtitleRo: 'Risc termic, manipulare, fotografie și eliberare',
      subtitleEn: 'Temperature risk, handling, photo and release',
      icon: Icons.eco_rounded,
      contexts: <String>{'fish', 'capture'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
      safetyCritical: true,
    ),
    FluviUtilityDefinition(
      id: 'safety.biosecurity',
      family: FluviUtilityFamily.rulesPermitsSafety,
      destination: AppDestination.safety,
      titleRo: 'Biosecuritate',
      titleEn: 'Biosecurity',
      subtitleRo: 'Verifică, curăță și usucă echipamentul între ape',
      subtitleEn: 'Check, clean and dry equipment between waters',
      icon: Icons.cleaning_services_rounded,
      contexts: <String>{'plan', 'review'},
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.localFirst,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
    ),
    FluviUtilityDefinition(
      id: 'account.profile',
      family: FluviUtilityFamily.accountSettings,
      destination: AppDestination.profile,
      titleRo: 'Profil',
      titleEn: 'Profile',
      subtitleRo: 'Identitate, preferințe și contribuții',
      subtitleEn: 'Identity, preferences and contributions',
      icon: Icons.person_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
      pinnable: false,
    ),
    FluviUtilityDefinition(
      id: 'account.settings',
      family: FluviUtilityFamily.accountSettings,
      destination: AppDestination.settings,
      titleRo: 'Setări',
      titleEn: 'Settings',
      subtitleRo: 'Limbă, regiune, temă, accesibilitate și notificări',
      subtitleEn: 'Language, region, theme, accessibility and notifications',
      icon: Icons.settings_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.localFirst,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
      pinnable: false,
    ),
    FluviUtilityDefinition(
      id: 'account.premium',
      family: FluviUtilityFamily.accountSettings,
      destination: AppDestination.premium,
      titleRo: 'Premium',
      titleEn: 'Premium',
      subtitleRo: 'Profunzime suplimentară pe aceleași rute',
      subtitleEn: 'Additional depth on the same routes',
      icon: Icons.workspace_premium_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.notApplicable,
      pinnable: false,
    ),
    FluviUtilityDefinition(
      id: 'account.support',
      family: FluviUtilityFamily.accountSettings,
      destination: AppDestination.support,
      titleRo: 'Ajutor și feedback',
      titleEn: 'Help & feedback',
      subtitleRo: 'Suport, contact și raportarea unei probleme',
      subtitleEn: 'Support, contact and reporting an issue',
      icon: Icons.support_agent_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.privateDefault,
      pinnable: false,
    ),
    FluviUtilityDefinition(
      id: 'account.legal',
      family: FluviUtilityFamily.accountSettings,
      destination: AppDestination.legal,
      titleRo: 'Confidențialitate și legal',
      titleEn: 'Privacy & legal',
      subtitleRo: 'Date, termeni, licențe și surse',
      subtitleEn: 'Data, terms, licences and sources',
      icon: Icons.privacy_tip_rounded,
      contexts: _allContexts,
      countryPacks: _global,
      entitlement: FluviEntitlementPolicy.free,
      offlinePolicy: FluviOfflinePolicy.cachedRead,
      privacyPolicy: FluviPrivacyPolicy.notApplicable,
      pinnable: false,
    ),
  ];

  static FluviUtilityDefinition byId(String id) =>
      definitions.firstWhere((definition) => definition.id == id);

  static List<FluviUtilityDefinition> forFamily(FluviUtilityFamily family) =>
      definitions
          .where((definition) => definition.family == family)
          .toList(growable: false);

  static List<FluviUtilityDefinition> search(
    String query, {
    required bool isRomanian,
  }) {
    final normalized = query.trim().toLowerCase();
    if (normalized.isEmpty) return definitions;
    return definitions
        .where((definition) {
          final haystack = <String>[
            definition.id,
            definition.title(isRomanian),
            definition.subtitle(isRomanian),
            definition.family.title(isRomanian),
          ].join(' ').toLowerCase();
          return haystack.contains(normalized);
        })
        .toList(growable: false);
  }
}
