-- FluviAI Water: source registry, staging parity and canonical mappings.
-- This migration is written locally first and must be reviewed before deployment.

create table if not exists public.water_measurements_latest_staging (
  source text not null,
  country_code text not null,
  source_station_id text not null,
  station_name text not null,
  river_name text,
  water_scope text,
  latitude double precision,
  longitude double precision,
  metric_code text not null,
  metric_name text,
  value double precision,
  unit text,
  availability_status text not null default 'available',
  source_age_text text,
  source_age_seconds_approx bigint,
  interval_hours double precision,
  trend text,
  exact_observed_at timestamptz,
  observed_at_precision text not null default 'relative',
  fetched_at timestamptz not null,
  source_url text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),

  constraint water_measurements_latest_staging_pkey
    primary key (source, country_code, source_station_id, metric_code),
  constraint water_measurements_latest_staging_availability_chk
    check (availability_status in ('available', 'temporarily_unavailable')),
  constraint water_measurements_latest_staging_country_code_chk
    check (char_length(country_code) = 2),
  constraint water_measurements_latest_staging_precision_chk
    check (observed_at_precision in ('exact', 'relative', 'unknown')),
  constraint water_measurements_latest_staging_value_chk
    check (
      (
        availability_status = 'available'
        and value is not null
        and unit is not null
      )
      or (
        availability_status = 'temporarily_unavailable'
        and value is null
      )
    )
);

create table if not exists public.water_observations_staging (
  id bigint generated by default as identity primary key,
  source text not null,
  source_url text not null,
  country_code text not null,
  river_name text not null,
  source_record_id bigint,
  source_record_uuid text,
  station_name text not null,
  station_key text not null,
  river_km numeric(8,2),
  water_level_cm numeric(10,2) not null,
  variation_cm_24h numeric(10,2),
  water_temperature_c numeric(5,2),
  observed_at timestamptz not null,
  forecast_updated_at timestamptz,
  latitude double precision,
  longitude double precision,
  forecasts jsonb not null default '[]'::jsonb,
  raw_payload jsonb,
  fetched_at timestamptz not null,
  ingested_at timestamptz not null default now(),

  constraint water_observations_staging_unique_observation
    unique (source, country_code, station_key, observed_at),
  constraint water_observations_staging_country_code_check
    check (country_code ~ '^[A-Z]{2}$'),
  constraint water_observations_staging_forecasts_check
    check (jsonb_typeof(forecasts) = 'array'),
  constraint water_observations_staging_latitude_check
    check (latitude is null or latitude between -90 and 90),
  constraint water_observations_staging_longitude_check
    check (longitude is null or longitude between -180 and 180),
  constraint water_observations_staging_level_check
    check (water_level_cm between -2000 and 5000),
  constraint water_observations_staging_variation_check
    check (variation_cm_24h is null or variation_cm_24h between -1000 and 1000),
  constraint water_observations_staging_temperature_check
    check (water_temperature_c is null or water_temperature_c between -10 and 50),
  constraint water_observations_staging_source_check
    check (length(btrim(source)) between 2 and 50),
  constraint water_observations_staging_station_key_check
    check (station_key ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint water_observations_staging_station_name_check
    check (length(btrim(station_name)) between 1 and 160)
);

create index if not exists water_observations_staging_fetched_at_idx
  on public.water_observations_staging (fetched_at desc);

create index if not exists water_observations_staging_source_time_idx
  on public.water_observations_staging (source, observed_at desc);

create index if not exists water_observations_staging_station_time_idx
  on public.water_observations_staging (
    country_code,
    station_key,
    observed_at desc
  );

alter table public.water_measurements_latest_staging enable row level security;
alter table public.water_observations_staging enable row level security;

revoke all privileges
  on table public.water_measurements_latest_staging
  from public, anon, authenticated;

revoke all privileges
  on table public.water_observations_staging
  from public, anon, authenticated;

grant select, insert, update, delete
  on table public.water_measurements_latest_staging
  to service_role;

grant select, insert, update, delete
  on table public.water_observations_staging
  to service_role;

grant usage, select
  on sequence public.water_observations_staging_id_seq
  to service_role;

create table if not exists public.water_station_source_mappings (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  country_code text not null,
  source_station_id text not null,
  station_id text not null,
  mapping_status text not null default 'verified',
  confidence text not null,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint water_station_source_mappings_confidence_check
    check (confidence in ('high', 'medium', 'low')),

  constraint water_station_source_mappings_country_code_check
    check (country_code ~ '^[A-Z]{2}$'),

  constraint water_station_source_mappings_provenance_object_check
    check (jsonb_typeof(provenance) = 'object'),

  constraint water_station_source_mappings_source_id_not_blank_check
    check (btrim(source_station_id) <> ''),

  constraint water_station_source_mappings_source_not_blank_check
    check (btrim(source) <> ''),

  constraint water_station_source_mappings_status_check
    check (mapping_status in ('verified', 'review_required')),

  constraint water_station_source_mappings_source_identity_unique
    unique (source, country_code, source_station_id),

  constraint water_station_source_mappings_station_fkey
    foreign key (station_id)
    references public.stations (id)
    on update cascade
    on delete restrict
);

comment on table public.water_station_source_mappings is
  'Maps one or more official provider station IDs to one canonical FluviAI station.';

create index if not exists water_station_source_mappings_station_idx
  on public.water_station_source_mappings (station_id);

drop trigger if exists water_station_source_mappings_set_updated_at
  on public.water_station_source_mappings;

create trigger water_station_source_mappings_set_updated_at
before update on public.water_station_source_mappings
for each row execute function public.set_updated_at();

alter table public.water_station_source_mappings enable row level security;

revoke all privileges
  on table public.water_station_source_mappings
  from public, anon, authenticated;

grant all privileges
  on table public.water_station_source_mappings
  to service_role;

create or replace function public.normalize_water_station_key(p_value text)
returns text
language sql
immutable
strict
set search_path = public, pg_temp
as $function$
  select regexp_replace(
    translate(
      lower(btrim(p_value)),
      'ăâáàäîíìïșşțţ',
      'aaaaaiiiisstt'
    ),
    '[^a-z0-9]+',
    '',
    'g'
  );
$function$;

revoke all
  on function public.normalize_water_station_key(text)
  from public, anon, authenticated;

grant execute
  on function public.normalize_water_station_key(text)
  to service_role;

insert into public.water_data_sources (
  source_key,
  display_name,
  authority_name,
  country_code,
  source_kind,
  acquisition_mode,
  rights_class,
  commercial_reuse_status,
  base_url,
  data_format,
  publication_cadence,
  freshness_target_minutes,
  collector_enabled,
  is_active,
  provenance
)
values
(
  'AFDJ',
  'AFDJ – Cotele apelor Dunării',
  'Administrația Fluvială a Dunării de Jos',
  'RO',
  'official_authority',
  'official_public',
  'public_display',
  'unknown',
  'https://www.afdj.ro',
  'XML',
  'daily',
  2160,
  false,
  true,
  jsonb_build_object(
    'existing_pipeline', 'github_vpn_ro',
    'role', 'canonical_primary',
    'legal_status_encoded_conservatively', true
  )
),
(
  'DanubeHIS',
  'DanubeHIS',
  'Danube Hydrological Information Services',
  'RO',
  'open_data_portal',
  'official_public',
  'public_display',
  'unknown',
  'https://www.danubehis.org',
  'HTML',
  'source_defined',
  2160,
  false,
  true,
  jsonb_build_object(
    'existing_pipeline', 'direct_backend',
    'role', 'canonical_fallback',
    'legal_status_encoded_conservatively', true
  )
),
(
  'DanubeFIS',
  'DanubeFIS / Danube Portal',
  'Danube FIS Portal',
  'RO',
  'system_operator',
  'official_public',
  'public_display',
  'unknown',
  'https://www.danubeportal.com',
  'HTML',
  'source_defined',
  2160,
  false,
  true,
  jsonb_build_object(
    'existing_pipeline', 'direct_backend',
    'role', 'fast_fallback',
    'legal_status_encoded_conservatively', true
  )
)
on conflict (source_key) do update
set
  display_name = excluded.display_name,
  authority_name = excluded.authority_name,
  country_code = excluded.country_code,
  source_kind = excluded.source_kind,
  base_url = excluded.base_url,
  data_format = excluded.data_format,
  publication_cadence = excluded.publication_cadence,
  freshness_target_minutes = excluded.freshness_target_minutes,
  is_active = true,
  provenance = public.water_data_sources.provenance || excluded.provenance,
  updated_at = now();

with canonical_afdj_mapping(source_station_id, station_id) as (
  values
    ('bazias', 'bazias'),
    ('moldova-veche', 'moldova_veche'),
    ('drencova', 'afdj-drencova'),
    ('orsova', 'orsova'),
    ('drobeta-turnu-severin', 'drobeta_turnu_severin'),
    ('gruia', 'afdj-gruia'),
    ('cetate', 'afdj-cetate'),
    ('calafat', 'calafat'),
    ('rast', 'afdj-rast'),
    ('bechet', 'bechet'),
    ('corabia', 'corabia'),
    ('turnu-magurele', 'turnu_magurele'),
    ('zimnicea', 'zimnicea'),
    ('giurgiu', 'giurgiu'),
    ('oltenita', 'oltenita'),
    ('calarasi', 'calarasi'),
    ('cernavoda', 'cernavoda'),
    ('harsova', 'harsova'),
    ('braila', 'braila'),
    ('galati', 'galati'),
    ('isaccea', 'isaccea'),
    ('tulcea', 'tulcea'),
    ('sulina', 'sulina')
)
insert into public.water_station_source_mappings (
  source,
  country_code,
  source_station_id,
  station_id,
  mapping_status,
  confidence,
  provenance
)
select
  'AFDJ',
  'RO',
  mapping.source_station_id,
  mapping.station_id,
  'verified',
  'high',
  jsonb_build_object(
    'origin', 'canonical_afdj_roster',
    'verified_rows', 23
  )
from canonical_afdj_mapping mapping
join public.stations station
  on station.id = mapping.station_id
on conflict (source, country_code, source_station_id) do update
set
  mapping_status = excluded.mapping_status,
  confidence = excluded.confidence,
  provenance =
    public.water_station_source_mappings.provenance
    || excluded.provenance,
  updated_at = now()
where public.water_station_source_mappings.station_id = excluded.station_id;

with canonical_station_ids(station_id) as (
  values
    ('bazias'),
    ('moldova_veche'),
    ('afdj-drencova'),
    ('orsova'),
    ('drobeta_turnu_severin'),
    ('afdj-gruia'),
    ('afdj-cetate'),
    ('calafat'),
    ('afdj-rast'),
    ('bechet'),
    ('corabia'),
    ('turnu_magurele'),
    ('zimnicea'),
    ('giurgiu'),
    ('oltenita'),
    ('calarasi'),
    ('cernavoda'),
    ('harsova'),
    ('braila'),
    ('galati'),
    ('isaccea'),
    ('tulcea'),
    ('sulina')
)
insert into public.water_station_source_mappings (
  source,
  country_code,
  source_station_id,
  station_id,
  mapping_status,
  confidence,
  provenance
)
select
  'DanubeFIS',
  'RO',
  public.normalize_water_station_key(station.name),
  station.id,
  'verified',
  'medium',
  jsonb_build_object(
    'origin', 'existing_flutter_normalized_name_contract',
    'identity_kind', 'normalized_station_name',
    'provider_station_id_available', false,
    'historical_snapshot_evidence', true,
    'evidence_window_start', '2026-07-16',
    'evidence_window_end', '2026-07-22',
    'canonical_stations_with_fis_rows', 23
  )
from canonical_station_ids roster
join public.stations station
  on station.id = roster.station_id
on conflict (source, country_code, source_station_id) do update
set
  mapping_status = excluded.mapping_status,
  confidence = excluded.confidence,
  provenance =
    public.water_station_source_mappings.provenance
    || excluded.provenance,
  updated_at = now()
where public.water_station_source_mappings.station_id = excluded.station_id;

with canonical_danubehis_mapping(
  source_station_id,
  station_id,
  provider_station_name
) as (
  values
    ('RO42001_HYDRO', 'bazias', 'Bazias'),
    ('RO42013_HYDRO', 'calafat', 'Calafat'),
    ('RO42027_HYDRO', 'giurgiu', 'Giurgiu'),
    ('RO42055_HYDRO', 'isaccea', 'Isaccea')
)
insert into public.water_station_source_mappings (
  source,
  country_code,
  source_station_id,
  station_id,
  mapping_status,
  confidence,
  provenance
)
select
  'DanubeHIS',
  'RO',
  mapping.source_station_id,
  mapping.station_id,
  'verified',
  'high',
  jsonb_build_object(
    'origin', 'danubehis_provider_id_audit',
    'identity_kind', 'provider_station_id',
    'provider_station_name', mapping.provider_station_name,
    'verification_method', 'provider_id_plus_unique_normalized_name',
    'verified_on', '2026-07-29',
    'observed_at_precision_in_latest_staging', 'relative',
    'exact_observed_at_available_in_latest_staging', false
  )
from canonical_danubehis_mapping mapping
join public.stations station
  on station.id = mapping.station_id
on conflict (source, country_code, source_station_id) do update
set
  mapping_status = excluded.mapping_status,
  confidence = excluded.confidence,
  provenance =
    public.water_station_source_mappings.provenance
    || excluded.provenance,
  updated_at = now()
where public.water_station_source_mappings.station_id = excluded.station_id;
-- Canonical operational observations are backend-only.
-- Mobile clients receive data exclusively through security-definer RPCs.
alter table public.water_operational_observations
  enable row level security;

revoke all privileges
  on table public.water_operational_observations
  from public, anon, authenticated, service_role;

grant select, insert
  on table public.water_operational_observations
  to service_role;

-- Required for deterministic SHA-256 source-record fingerprints.
-- Declared here so a fresh database does not depend on preinstalled extensions.
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- Promote normalized AFDJ staging observations into the canonical,
-- append-only operational Water store.
create or replace function public.promote_afdj_water_level_observations()
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  inserted_rows integer := 0;
begin
  if not exists (
    select 1
    from public.water_data_sources
    where source_key = 'AFDJ'
      and country_code = 'RO'
      and is_active
  ) then
    raise exception
      'AFDJ promotion failed: active source registry entry is missing.';
  end if;

  if exists (
    select 1
    from public.water_observations_staging staging
    left join public.water_station_source_mappings mapping
      on mapping.source = staging.source
     and mapping.country_code = staging.country_code
     and mapping.source_station_id = staging.station_key
     and mapping.mapping_status = 'verified'
    where staging.source = 'AFDJ'
      and staging.country_code = 'RO'
      and mapping.station_id is null
  ) then
    raise exception
      'AFDJ promotion failed: one or more staging stations are not verified.';
  end if;

  insert into public.water_operational_observations (
    source_id,
    country_code,
    source_entity_id,
    station_id,
    metric_code,
    metric_name,
    value,
    unit,
    availability_status,
    observed_at,
    observed_at_precision,
    quality_status,
    confidence,
    source_record_id,
    source_record_fingerprint,
    source_url,
    ingestion_run_id,
    fetched_at,
    raw_payload
  )
  select
    source_registry.id,
    staging.country_code,
    staging.station_key,
    mapping.station_id,
    'water_level_cm',
    'Water level',
    staging.water_level_cm,
    'cm',
    'available',
    staging.observed_at,
    'exact',
    'validated',
    'high',
    coalesce(
      staging.source_record_uuid,
      staging.source_record_id::text,
      staging.id::text
    ),
    encode(
      digest(
        concat_ws(
          '|',
          staging.source,
          staging.country_code,
          staging.station_key,
          'water_level_cm',
          extract(epoch from staging.observed_at)::text,
          staging.water_level_cm::text,
          coalesce(
            staging.source_record_uuid,
            staging.source_record_id::text,
            ''
          )
        ),
        'sha256'
      ),
      'hex'
    ),
    staging.source_url,
    concat(
      'afdj-staging-',
      to_char(
        staging.ingested_at at time zone 'UTC',
        'YYYYMMDDHH24MISS'
      )
    ),
    staging.fetched_at,
    coalesce(staging.raw_payload, '{}'::jsonb)
      || jsonb_build_object(
        'promoted_from', 'water_observations_staging',
        'staging_id', staging.id
      )
  from public.water_observations_staging staging
  join public.water_data_sources source_registry
    on source_registry.source_key = staging.source
   and source_registry.country_code = staging.country_code
   and source_registry.is_active
  join public.water_station_source_mappings mapping
    on mapping.source = staging.source
   and mapping.country_code = staging.country_code
   and mapping.source_station_id = staging.station_key
   and mapping.mapping_status = 'verified'
  where staging.source = 'AFDJ'
    and staging.country_code = 'RO'
  on conflict (
    source_id,
    source_entity_id,
    metric_code,
    source_record_fingerprint
  ) do nothing;

  get diagnostics inserted_rows = row_count;
  return inserted_rows;
end;
$$;

revoke all
  on function public.promote_afdj_water_level_observations()
  from public, anon, authenticated;

grant execute
  on function public.promote_afdj_water_level_observations()
  to service_role;

select public.promote_afdj_water_level_observations();

do $$
declare
  promoted_station_count integer;
begin
  select count(distinct observation.station_id)
  into promoted_station_count
  from public.water_operational_observations observation
  join public.water_data_sources source_registry
    on source_registry.id = observation.source_id
  where source_registry.source_key = 'AFDJ'
    and source_registry.country_code = 'RO'
    and observation.metric_code = 'water_level_cm'
    and observation.availability_status = 'available';

  if promoted_station_count <> 23 then
    raise exception
      'AFDJ promotion postcondition failed: expected 23 stations, found %.',
      promoted_station_count;
  end if;
end;
$$;

-- Stable mobile read contract. Raw and operational tables remain private.
create or replace function public.get_water_station_latest_v1(
  p_station_id text default null
)
returns table (
  station_id text,
  station_name text,
  river_name text,
  latitude double precision,
  longitude double precision,
  display_order integer,
  level_cm numeric,
  observed_at timestamptz,
  observed_at_precision text,
  source_key text,
  source_name text,
  source_url text,
  quality_status text,
  confidence text,
  fetched_at timestamptz,
  freshness_minutes integer,
  is_stale boolean
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  with ranked as (
    select
      observation.*,
      source_registry.source_key,
      source_registry.display_name as source_name,
      source_registry.freshness_target_minutes,
      row_number() over (
        partition by observation.station_id
        order by
          observation.observed_at desc nulls last,
          observation.fetched_at desc,
          observation.created_at desc
      ) as row_rank
    from public.water_operational_observations observation
    join public.water_data_sources source_registry
      on source_registry.id = observation.source_id
     and source_registry.country_code = observation.country_code
     and source_registry.is_active
    where observation.station_id is not null
      and observation.metric_code = 'water_level_cm'
      and observation.availability_status = 'available'
      and observation.quality_status in ('validated', 'corrected')
      and (
        p_station_id is null
        or observation.station_id = p_station_id
      )
  )
  select
    station.id,
    station.name,
    station.river,
    station.latitude,
    station.longitude,
    station.display_order,
    latest.value,
    latest.observed_at,
    latest.observed_at_precision,
    latest.source_key,
    latest.source_name,
    latest.source_url,
    latest.quality_status,
    latest.confidence,
    latest.fetched_at,
    floor(
      greatest(
        0,
        extract(epoch from (now() - latest.observed_at)) / 60.0
      )
    )::integer,
    latest.observed_at <
      now() - make_interval(
        mins => coalesce(latest.freshness_target_minutes, 2160)
      )
  from ranked latest
  join public.stations station
    on station.id = latest.station_id
  where latest.row_rank = 1
  order by
    station.display_order nulls last,
    station.name;
$$;

comment on function public.get_water_station_latest_v1(text) is
  'Secure Water mobile contract returning the latest canonical water-level observation per station.';

revoke all
  on function public.get_water_station_latest_v1(text)
  from public;

grant execute
  on function public.get_water_station_latest_v1(text)
  to anon, authenticated, service_role;


create or replace function public.get_water_station_history_v1(
  p_station_id text,
  p_days integer default 30
)
returns table (
  station_id text,
  level_cm numeric,
  observed_at timestamptz,
  observed_at_precision text,
  source_key text,
  quality_status text,
  confidence text,
  fetched_at timestamptz,
  data_origin text
)
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
begin
  if p_station_id is null or btrim(p_station_id) = '' then
    raise exception 'Water history requires a station id.';
  end if;

  if p_days < 1 or p_days > 366 then
    raise exception 'Water history days must be between 1 and 366.';
  end if;

  return query
  with candidates as (
    select
      observation.station_id,
      observation.value as level_cm,
      observation.observed_at,
      observation.observed_at_precision,
      source_registry.source_key,
      observation.quality_status,
      observation.confidence,
      observation.fetched_at,
      'operational'::text as data_origin,
      1 as source_priority
    from public.water_operational_observations observation
    join public.water_data_sources source_registry
      on source_registry.id = observation.source_id
     and source_registry.country_code = observation.country_code
    where observation.station_id = p_station_id
      and observation.metric_code = 'water_level_cm'
      and observation.availability_status = 'available'
      and observation.quality_status in ('validated', 'corrected')
      and observation.observed_at >=
        now() - make_interval(days => p_days)

    union all

    select
      snapshot.station_id,
      snapshot.level_cm::numeric,
      coalesce(
        snapshot.level_measured_at,
        snapshot.observation_date::timestamp at time zone 'UTC'
      ),
      case
        when snapshot.level_measured_at is not null then 'exact'
        else 'date'
      end,
      coalesce(nullif(snapshot.level_source, ''), 'legacy_snapshot'),
      case lower(snapshot.quality)
        when 'valid' then 'validated'
        when 'partial' then 'raw'
        else 'suspect'
      end,
      case lower(snapshot.quality)
        when 'valid' then 'high'
        when 'partial' then 'medium'
        else 'low'
      end,
      snapshot.fetched_at,
      'daily_snapshot'::text,
      2
    from public.daily_water_snapshots snapshot
    where snapshot.station_id = p_station_id
      and snapshot.level_cm is not null
      and coalesce(
        snapshot.level_measured_at,
        snapshot.observation_date::timestamp at time zone 'UTC'
      ) >= now() - make_interval(days => p_days)
  ),
  ranked as (
    select
      candidate.*,
      row_number() over (
        partition by candidate.station_id, candidate.observed_at
        order by
          candidate.source_priority,
          candidate.fetched_at desc
      ) as row_rank
    from candidates candidate
  )
  select
    ranked.station_id,
    ranked.level_cm,
    ranked.observed_at,
    ranked.observed_at_precision,
    ranked.source_key,
    ranked.quality_status,
    ranked.confidence,
    ranked.fetched_at,
    ranked.data_origin
  from ranked
  where ranked.row_rank = 1
  order by ranked.observed_at asc;
end;
$$;

comment on function public.get_water_station_history_v1(text, integer) is
  'Secure Water mobile history contract combining canonical operational observations with preserved legacy snapshots.';

revoke all
  on function public.get_water_station_history_v1(text, integer)
  from public;

grant execute
  on function public.get_water_station_history_v1(text, integer)
  to anon, authenticated, service_role;


do $$
declare
  latest_station_count integer;
begin
  select count(*)
  into latest_station_count
  from public.get_water_station_latest_v1(null);

  if latest_station_count <> 23 then
    raise exception
      'Water latest contract postcondition failed: expected 23 stations, found %.',
      latest_station_count;
  end if;
end;
$$;