-- One idempotent daily water snapshot per station and Europe/Bucharest date.
-- The collector upserts on (station_id, observation_date); it must not insert
-- more than one row for the same station and day.
-- Manual rollback: use a separately approved migration after reviewing whether
-- the newly collected observations should be archived or removed.

create table if not exists public.daily_water_snapshots (
  id bigint generated by default as identity primary key,
  station_id text not null,
  observation_date date not null,

  level_cm integer,
  level_source text,
  level_measured_at timestamptz,

  daily_delta_cm integer,
  delta_source text,
  delta_measured_at timestamptz,
  delta_base_measured_at timestamptz,
  delta_method text not null default 'unavailable',
  quality text not null default 'unknown',

  fetched_at timestamptz not null default now(),
  parser_version text,
  raw_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint daily_water_snapshots_station_id_fkey
    foreign key (station_id)
    references public.stations(id)
    on update cascade
    on delete restrict,
  constraint daily_water_snapshots_station_date_key
    unique (station_id, observation_date),
  constraint daily_water_snapshots_delta_method_check
    check (delta_method in (
      'provider_reported',
      'computed_same_source',
      'unavailable'
    )),
  constraint daily_water_snapshots_quality_check
    check (quality in (
      'valid',
      'partial',
      'stale',
      'provider_error',
      'unknown'
    )),
  constraint daily_water_snapshots_level_source_check
    check (level_source is null or level_source in (
      'AFDJ',
      'DanubeHIS',
      'DanubeFIS'
    )),
  constraint daily_water_snapshots_delta_source_check
    check (delta_source is null or delta_source in (
      'AFDJ',
      'DanubeHIS',
      'DanubeFIS'
    )),
  constraint daily_water_snapshots_level_pairing_check
    check (
      (level_cm is null and level_source is null and level_measured_at is null) or
      (level_cm is not null and level_source is not null and level_measured_at is not null)
    ),
  constraint daily_water_snapshots_delta_pairing_check
    check (
      (daily_delta_cm is null and delta_method = 'unavailable' and
        delta_source is null and delta_measured_at is null and
        delta_base_measured_at is null) or
      (daily_delta_cm is not null and delta_method = 'provider_reported' and
        delta_source is not null and delta_measured_at is not null and
        delta_base_measured_at is null) or
      (daily_delta_cm is not null and delta_method = 'computed_same_source' and
        delta_source is not null and delta_measured_at is not null and
        delta_base_measured_at is not null)
    )
);

-- A pre-existing table is accepted only when it has this migration's core
-- contract. Otherwise fail clearly instead of silently using another schema.
do $$
declare
  missing_column text;
  missing_constraint text;
begin
  select required.column_name
    into missing_column
  from (
    values
      ('id', 'bigint', 'NO'),
      ('station_id', 'text', 'NO'),
      ('observation_date', 'date', 'NO'),
      ('level_cm', 'integer', 'YES'),
      ('level_source', 'text', 'YES'),
      ('level_measured_at', 'timestamp with time zone', 'YES'),
      ('daily_delta_cm', 'integer', 'YES'),
      ('delta_source', 'text', 'YES'),
      ('delta_measured_at', 'timestamp with time zone', 'YES'),
      ('delta_base_measured_at', 'timestamp with time zone', 'YES'),
      ('delta_method', 'text', 'NO'),
      ('quality', 'text', 'NO'),
      ('fetched_at', 'timestamp with time zone', 'NO'),
      ('parser_version', 'text', 'YES'),
      ('raw_hash', 'text', 'YES'),
      ('created_at', 'timestamp with time zone', 'NO'),
      ('updated_at', 'timestamp with time zone', 'NO')
  ) as required(column_name, data_type, is_nullable)
  left join information_schema.columns as actual
    on actual.table_schema = 'public'
    and actual.table_name = 'daily_water_snapshots'
    and actual.column_name = required.column_name
  where actual.column_name is null
    or actual.data_type <> required.data_type
    or actual.is_nullable <> required.is_nullable
  limit 1;

  if missing_column is not null then
    raise exception
      'daily_water_snapshots has an incompatible column contract at %',
      missing_column;
  end if;

  select required.constraint_name
    into missing_constraint
  from (
    values
      ('daily_water_snapshots_station_id_fkey'),
      ('daily_water_snapshots_station_date_key'),
      ('daily_water_snapshots_delta_method_check'),
      ('daily_water_snapshots_quality_check'),
      ('daily_water_snapshots_level_source_check'),
      ('daily_water_snapshots_delta_source_check'),
      ('daily_water_snapshots_level_pairing_check'),
      ('daily_water_snapshots_delta_pairing_check')
  ) as required(constraint_name)
  left join pg_constraint as actual
    on actual.conrelid = 'public.daily_water_snapshots'::regclass
    and actual.conname = required.constraint_name
  where actual.oid is null
  limit 1;

  if missing_constraint is not null then
    raise exception
      'daily_water_snapshots has a missing required constraint %',
      missing_constraint;
  end if;
end;
$$;

create index if not exists daily_water_snapshots_station_date_desc_idx
  on public.daily_water_snapshots (station_id, observation_date desc);

create index if not exists daily_water_snapshots_observation_date_desc_idx
  on public.daily_water_snapshots (observation_date desc);

create index if not exists daily_water_snapshots_quality_idx
  on public.daily_water_snapshots (quality);

alter table public.daily_water_snapshots enable row level security;

revoke all privileges
  on table public.daily_water_snapshots
  from anon, authenticated;

grant select
  on table public.daily_water_snapshots
  to anon, authenticated;

drop policy if exists "daily_water_snapshots_public_read"
  on public.daily_water_snapshots;

create policy "daily_water_snapshots_public_read"
  on public.daily_water_snapshots
  for select
  to anon, authenticated
  using (true);

-- public.set_updated_at already exists in the database foundation migration.
drop trigger if exists daily_water_snapshots_set_updated_at
  on public.daily_water_snapshots;

create trigger daily_water_snapshots_set_updated_at
  before update on public.daily_water_snapshots
  for each row execute function public.set_updated_at();

comment on table public.daily_water_snapshots is
  'Daily station snapshots. Conflict key is (station_id, observation_date) for collector upserts.';

comment on column public.daily_water_snapshots.level_cm is
  'Absolute water level in centimetres; it is secondary to the daily delta for angler decisions.';

comment on column public.daily_water_snapshots.level_source is
  'Source of level_cm. It remains independent from delta_source.';

comment on column public.daily_water_snapshots.level_measured_at is
  'Measurement timestamp for level_cm; never treated as the delta timestamp.';

comment on column public.daily_water_snapshots.daily_delta_cm is
  'Primary angler metric: real centimetre change versus the compatible prior observation.';

comment on column public.daily_water_snapshots.delta_source is
  'Source of daily_delta_cm. It may differ from level_source.';

comment on column public.daily_water_snapshots.delta_measured_at is
  'Measurement timestamp reported for the delta; independent from level_measured_at.';

comment on column public.daily_water_snapshots.delta_base_measured_at is
  'Earlier compatible measurement used only when delta_method is computed_same_source.';

comment on column public.daily_water_snapshots.delta_method is
  'provider_reported, computed_same_source, or unavailable; stable is never inferred without a real delta.';
