-- FluviAI Water Intelligence: explicit evidence classes on numeric observations.
-- Existing observations remain MEASURED. Community/Reports remain separate OBSERVED evidence.
-- UNKNOWN is generated by read contracts and is never stored as a fabricated numeric row.

alter table public.water_operational_observations
  add column if not exists evidence_state text not null default 'MEASURED';

comment on column public.water_operational_observations.evidence_state is
  'Numeric evidence class: MEASURED, DERIVED, or ESTIMATED. OBSERVED belongs to Community/Reports; UNKNOWN is emitted when no evidence exists.';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.water_operational_observations'::regclass
      and conname = 'water_operational_observations_evidence_state_check'
  ) then
    alter table public.water_operational_observations
      add constraint water_operational_observations_evidence_state_check
      check (evidence_state in ('MEASURED','DERIVED','ESTIMATED'));
  end if;
end $$;

create or replace function public.get_water_entity_metric_availability_v1(
  p_entity_type text,
  p_entity_id text
)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_type text := lower(btrim(coalesce(p_entity_type,'')));
  v_station text;
  v_dam uuid;
  v_reservoir uuid;
  v_water_body uuid;
  v_river_key text;
  v_result jsonb;
begin
  if v_type = 'station' then
    v_station := p_entity_id;
    if not exists (select 1 from public.stations where id=v_station) then
      raise exception 'Unknown station entity';
    end if;
  elsif v_type = 'dam' then
    v_dam := p_entity_id::uuid;
    select water_body_id into v_water_body from public.dams where id=v_dam;
    if v_water_body is null then raise exception 'Unknown dam entity'; end if;
  elsif v_type = 'reservoir' then
    v_reservoir := p_entity_id::uuid;
    select water_body_id into v_water_body from public.reservoirs where id=v_reservoir;
    if v_water_body is null then raise exception 'Unknown reservoir entity'; end if;
  elsif v_type = 'water_body' then
    v_water_body := p_entity_id::uuid;
    if not exists (select 1 from public.water_bodies where id=v_water_body) then
      raise exception 'Unknown water_body entity';
    end if;
  elsif v_type = 'river' then
    v_river_key := p_entity_id;
    select water_body_id into v_water_body
    from public.water_river_index_v2
    where river_key=v_river_key
    limit 1;
    if v_water_body is null then raise exception 'Unknown river entity'; end if;
  else
    raise exception 'Unsupported water entity type: %', p_entity_type;
  end if;

  with metric_catalog(metric_code, metric_name, canonical_unit, metric_kind, community_field) as (
    values
      ('water_level_cm','Water level','cm','numeric',null::text),
      ('water_level_trend','Water level trend',null,'qualitative','level_trend'),
      ('discharge_m3s','Discharge','m3/s','numeric',null),
      ('flow_state','Flow state',null,'qualitative','flow_state'),
      ('reservoir_level_m','Reservoir level','m','numeric',null),
      ('fill_percent','Reservoir fill','%','numeric',null),
      ('inflow_m3s','Reservoir inflow','m3/s','numeric',null),
      ('outflow_m3s','Reservoir outflow','m3/s','numeric',null),
      ('water_temperature_c','Water temperature','C','numeric',null),
      ('operation_signal','Hydropower / operation signal',null,'qualitative','operation_signal'),
      ('hydropower_generation_mw','Hydropower generation','MW','numeric',null)
  ),
  entity_obs as (
    select o.*, ds.source_key, ds.display_name as source_name, ds.authority_name,
           row_number() over (
             partition by o.metric_code
             order by coalesce(o.observed_at,o.fetched_at) desc, o.fetched_at desc
           ) as rn
    from public.water_operational_observations o
    join public.water_data_sources ds on ds.id=o.source_id
    where (v_station is not null and o.station_id=v_station)
       or (v_dam is not null and o.dam_id=v_dam)
       or (v_reservoir is not null and o.reservoir_id=v_reservoir)
       or (v_water_body is not null and o.water_body_id=v_water_body)
  ),
  direct_latest as (
    select * from entity_obs where rn=1
  ),
  level_basis as (
    select * from entity_obs
    where metric_code='water_level_cm'
      and evidence_state='MEASURED'
    order by coalesce(observed_at,fetched_at) desc
    limit 1
  ),
  community_candidates as (
    select w.*, r.still_valid_count, r.no_longer_valid_count,
           least(1.0,
             coalesce(w.classification_confidence,0.40)
             + least(coalesce(r.still_valid_count,0),3)*0.08
             - least(coalesce(r.no_longer_valid_count,0),3)*0.10
           ) as effective_confidence
    from public.water_community_observations w
    join public.reports r on r.id=w.report_id
    left join public.dams d on d.id=w.dam_id
    left join public.reservoirs rr on rr.id=w.reservoir_id
    left join public.stations s on s.id=w.station_id
    where r.is_suspicious=false
      and (r.expires_at is null or r.expires_at >= now()-interval '24 hours')
      and (
        (v_station is not null and w.station_id=v_station)
        or (v_dam is not null and w.dam_id=v_dam)
        or (v_reservoir is not null and w.reservoir_id=v_reservoir)
        or (v_water_body is not null and (
             w.water_body_id=v_water_body
             or d.water_body_id=v_water_body
             or rr.water_body_id=v_water_body
             or s.water_body_id=v_water_body
             or (v_river_key is not null and w.river_key=v_river_key)
           ))
      )
  ),
  best_community as (
    select * from community_candidates
    order by effective_confidence desc, observed_at desc
    limit 1
  ),
  rows as (
    select
      m.metric_code,
      m.metric_name,
      m.canonical_unit,
      m.metric_kind,
      case
        when dl.metric_code is not null and dl.availability_status='available'
          then dl.evidence_state
        when m.metric_code='water_level_trend'
             and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then 'DERIVED'
        when m.community_field='level_trend'
             and coalesce(bc.level_trend,'unknown') <> 'unknown' then 'OBSERVED'
        when m.community_field='flow_state'
             and coalesce(bc.flow_state,'unknown') <> 'unknown' then 'OBSERVED'
        when m.community_field='operation_signal'
             and coalesce(bc.operation_signal,'unknown') <> 'unknown' then 'OBSERVED'
        else 'UNKNOWN'
      end as evidence_state,
      case
        when dl.metric_code is not null and dl.availability_status='available' then dl.value
        else null
      end as numeric_value,
      case
        when dl.metric_code is not null and dl.availability_status='available' then dl.unit
        when m.metric_code='water_level_trend'
             and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then null
        else m.canonical_unit
      end as unit,
      case
        when m.metric_code='water_level_trend'
             and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then
          case
            when (lb.raw_payload->>'variation_cm_24h')::numeric > 0 then 'rising'
            when (lb.raw_payload->>'variation_cm_24h')::numeric < 0 then 'falling'
            else 'stable'
          end
        when m.community_field='level_trend' and coalesce(bc.level_trend,'unknown') <> 'unknown' then bc.level_trend
        when m.community_field='flow_state' and coalesce(bc.flow_state,'unknown') <> 'unknown' then bc.flow_state
        when m.community_field='operation_signal' and coalesce(bc.operation_signal,'unknown') <> 'unknown' then bc.operation_signal
        else null
      end as qualitative_value,
      case
        when dl.metric_code is not null and dl.availability_status='available' then dl.observed_at
        when m.metric_code='water_level_trend' and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then lb.observed_at
        when m.community_field is not null then bc.observed_at
        else null
      end as evidence_at,
      case
        when dl.metric_code is not null and dl.availability_status='available' then dl.fetched_at
        when m.metric_code='water_level_trend' and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then lb.fetched_at
        else null
      end as fetched_at,
      case
        when dl.metric_code is not null and dl.availability_status='available' then dl.source_key
        when m.metric_code='water_level_trend' and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then lb.source_key
        when m.community_field is not null and bc.report_id is not null then 'community_reports'
        else null
      end as source_key,
      case
        when dl.metric_code is not null and dl.availability_status='available' then dl.source_name
        when m.metric_code='water_level_trend' and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then lb.source_name
        when m.community_field is not null and bc.report_id is not null then 'Community reports'
        else null
      end as source_name,
      case
        when dl.metric_code is not null and dl.availability_status='available' then dl.source_url
        else null
      end as source_url,
      case
        when dl.metric_code is not null and dl.availability_status='available' then dl.confidence
        when m.metric_code='water_level_trend' and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then lb.confidence
        when m.community_field is not null and bc.report_id is not null then
          case when bc.effective_confidence >= 0.80 then 'high'
               when bc.effective_confidence >= 0.55 then 'medium'
               else 'low' end
        else 'unknown'
      end as confidence,
      case
        when dl.metric_code is not null and dl.availability_status='available' then dl.quality_status
        when m.metric_code='water_level_trend' and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then 'derived_from_measured'
        when m.community_field is not null and bc.report_id is not null then 'community_observed'
        else 'unavailable'
      end as quality_status,
      case
        when dl.metric_code is not null and dl.availability_status='available' then
          greatest(0, extract(epoch from (now()-coalesce(dl.observed_at,dl.fetched_at)))/60)::bigint
        when m.metric_code='water_level_trend' and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then
          greatest(0, extract(epoch from (now()-coalesce(lb.observed_at,lb.fetched_at)))/60)::bigint
        when m.community_field is not null and bc.report_id is not null then
          greatest(0, extract(epoch from (now()-bc.observed_at))/60)::bigint
        else null
      end as age_minutes,
      case
        when dl.metric_code is not null and dl.availability_status='available' then
          case dl.evidence_state
            when 'MEASURED' then 'measured_numeric'
            when 'DERIVED' then 'derived_numeric'
            when 'ESTIMATED' then 'model_estimated_numeric'
            else 'unknown_numeric'
          end
        when m.metric_code='water_level_trend' and nullif(lb.raw_payload->>'variation_cm_24h','') is not null then 'measured_derived'
        when m.community_field is not null and bc.report_id is not null then 'community_qualitative'
        else 'no_current_evidence'
      end as provenance_class
    from metric_catalog m
    left join direct_latest dl on dl.metric_code=m.metric_code
    left join level_basis lb on true
    left join best_community bc on true
  )
  select jsonb_build_object(
    'contract_version','1.1',
    'entity_type',v_type,
    'entity_id',p_entity_id,
    'generated_at',now(),
    'rules',jsonb_build_object(
      'numeric_truth','explicit_evidence_class_required',
      'measured','direct_measurement_or_official_observation',
      'derived','calculated_from_valid_evidence',
      'estimated','emitted_only_with_explicit_model_or_remote_sensing_evidence',
      'community','qualitative_observed_only',
      'unknown','preferred_over_fabrication'
    ),
    'metrics',coalesce(jsonb_agg(jsonb_build_object(
      'metric_code',metric_code,
      'metric_name',metric_name,
      'metric_kind',metric_kind,
      'evidence_state',evidence_state,
      'value',numeric_value,
      'unit',unit,
      'qualitative_value',qualitative_value,
      'evidence_at',evidence_at,
      'fetched_at',fetched_at,
      'age_minutes',age_minutes,
      'source_key',source_key,
      'source_name',source_name,
      'source_url',source_url,
      'confidence',confidence,
      'quality_status',quality_status,
      'provenance_class',provenance_class
    ) order by metric_code),'[]'::jsonb)
  ) into v_result
  from rows;

  return v_result;
end;
$function$;

revoke all on function public.get_water_entity_metric_availability_v1(text,text) from public;
grant execute on function public.get_water_entity_metric_availability_v1(text,text) to authenticated, service_role;
